### ISSUE TITLE
Upgrade to anchor 0.29.0

### ISSUE THREAD

**Issue by metaproph3t** [openbook-dex/openbook-v2#232]
Is this possible? It would allow me to upgrade [openbook-twap](https://github.com/metaDAOproject/openbook-twap) to 0.29.0, which would save on rent costs.

**Comment by skrrb** [comment]
there's #218 but tbh i'm not sure when it'll be merged/deployed. anyways, if it's only for the cpi intefaces, maybe you can just point to that particular branch, or even use [this tool](https://crates.io/crates/anchor-gen)

**Comment by metaproph3t** [comment]
cool thanks, will try that out!

**Comment by mschneider** [comment]
the upgrade has been merged @metaproph3t
