### ISSUE TITLE
Error when create market id but it still cost me 0.2sol. can i get a refund?

### ISSUE THREAD

**Issue by cateegit** [openbook-dex/openbook-v2#233]
![image](https://github.com/openbook-dex/openbook-v2/assets/95419437/8737d080-21c9-4b13-9dbd-5e4f8b4bf199)
tx: 45kdQaftDScbqEYM1jcbAoo5nsciHhX49fBzRFK13ar7VKiTq5PktYgDc7aa2ykU9Mgysnb8zwoZCkysogNNA6k5

btw discord invite link was expired :)

**Comment by Code4Zelda** [comment]
Same just happen to me smh . i hope this isnt a spam 
![Uploading Screenshot 2024-03-12 at 9.52.38 PM.png…]()

**Comment by Akidse** [comment]
I got the same error  - "Your transaction was unsuccessful".  How to get refund? Tx id: 4zgRYw1JqufCumVGGSRQQ4ZNsDws4kzoDyecc7x9tyrbPra5ufAh5gnvqiz5VXtySJNWSg1FF33EEa6hv2zizHTC

**Comment by skrrb** [comment]
which website are you using? that doesn't seem to be an error related with openbook-v2

**Comment by cateegit** [comment]
> which website are you using? that doesn't seem to be an error related with openbook-v2

https://www.openbookmarket.space/

**Comment by skrrb** [comment]
that site is a scam, and is not affiliated with openbook in any way. you can check an official list of v1 & v2 partners in the [openbook discord](https://t.co/lS5UgJNZuM)

**Comment by Code4Zelda** [comment]
i used https://www.openbookgui.com/error/

**Comment by Code4Zelda** [comment]
@skrrb
