### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Code4Zelda** [openbook-dex/openbook-v2#234]
Hello 
I used https://www.openbookgui.com
and got a error https://www.openbookgui.com/error/

<img width="1481" alt="Screenshot 2024-03-12 at 9 52 38 PM" src="https://github.com/openbook-dex/openbook-v2/assets/26892088/db895ee7-b5bc-43dc-b65e-99032c186de9">

Could you help? It happen TWICE! .5 SOL

**Comment by Code4Zelda** [comment]
@skrrb

**Comment by mschneider** [comment]
looks like you got scammed by someone with no affiliation to the openbook project. you will need to contact the openbookgui.com operators.
