### ISSUE TITLE
Error on creating market ID GVh5gdSWdLV32MmK1ytD8BTZC78ikjLLw8uq3DGTDZjZ

### ISSUE THREAD

**Issue by karloseq** [openbook-dex/openbook-v2#235]
I paid for creating openbook and got error

Please refund 0.2 fee to GVh5gdSWdLV32MmK1ytD8BTZC78ikjLLw8uq3DGTDZjZ

https://solscan.io/tx/2uneWMzP7ahyDmyhm8Ut5NbWc5ukKYXDmZKoZNfoAN112dkyEZyWz4d73deUA6oTSyCvFYZDE3nsenjjW4hXATuB

**Comment by karloseq** [comment]
![Uploading Screenshot 2024-03-14 110429 error.png…]()

**Comment by karloseq** [comment]
I will be forced to report this to police if founds you charged wont be refunded

**Comment by mschneider** [comment]
you should, looks like you got scammed by someone with no affiliation to the openbook project!
