### ISSUE TITLE
Transaction Failed Please Refund 0.25 SOL

### ISSUE THREAD

**Issue by itsmrsolucky** [openbook-dex/openbook-v2#239]
![image](https://github.com/openbook-dex/openbook-v2/assets/163956527/6fdd71d0-29de-4030-90cc-e8bbb5d07b9c)

![image](https://github.com/openbook-dex/openbook-v2/assets/163956527/baccbd0a-7c97-42fd-bfb3-4b473de7c56d)

Sent From: 6UrYREJShX5k8wFQpf5ZQJNQT6pcPPstaHkNppz7Yi8w

Transaction ID: https://solscan.io/tx/5NpsLb27q3q3kS64dKKJraF2tTmVFzrGKfu57TK4iZRgTe24qDzasQt2GKVyZrg7HfpsXcUWWS56vEwdGmyePPp8

**Comment by mschneider** [comment]
looks like you got scammed by someone with no affiliation to the openbook project. you will need to contact the openlab operators.
