### ISSUE TITLE
uncompleted operation

### ISSUE THREAD

**Issue by annurax** [openbook-dex/openbook-v2#243]
I have created an openbook market ID for my ANBL token and regularly paid the 0.2 SOL fee.
Unfortunately the operation was not completed by openbook even if the fee transaction was completed.
How can I recover my market ID?
Sugnature on solscan: 3dkK6WT8EtJrvM9B6PjuDUUj7q9KUgFugWYEYehUf8m4Ft4mH9itvUPrsrL6NQkHDvaZ1LoJZpps73AAXtdPAt4f
Thanks

**Comment by mschneider** [comment]
looks like you got scammed by someone with no affiliation to the openbook project! there's people out there who are running scam sites that charge 0.2 sol.

**Comment by annurax** [comment]
https://www.openbookdex.space like this one?

**Comment by mschneider** [comment]
Correct

**Comment by annurax** [comment]
a lesson to learn....

**Comment by annurax** [comment]
any suggestion to create a market id?

**Comment by mschneider** [comment]
this works for me https://beta.dual.finance/openbook
