### ISSUE TITLE
I used openbookdex create my  Openbook Market ID,but happend an error

### ISSUE THREAD

**Issue by sklfihggczx** [openbook-dex/openbook-v2#252]
I used https://www.openbookdex.space/  create my Create Openbook Market ID,but I can't recive my Openbook Market ID,
can you help me check it, my transfer tx  49JvA3KZNFE14zizWGniLF6a3VoG8SFFatCN7NXXnYXpiSTJw2qvJVCxjB1Ntwz4NRporrDoV47e3ZuxrJs5zEh1

my wallet AjdFN9Pd3CaBH5XXcXohV2KpB9WzNBqYfbytjSa9Uocm

**Comment by riordanp** [comment]
this is a scam website unrelated to the project, apologies
