### ISSUE TITLE
Using TS client import error

### ISSUE THREAD

**Issue by LukasDeco** [openbook-dex/openbook-v2#255]
I am having issues building with the latest version of the TS client. (0.2.5)
```
./node_modules/@openbook-dex/openbook-v2/dist/esm/utils/utils.js
Attempted import error: 'Wallet' is not exported from '@coral-xyz/anchor' (imported as 'Wallet').
```

Has anyone seen similar issues? I am using nextjs for building. I can't seem to get this to work right now.

Update: I was able to successfully recreate the issue with a brand new nextjs app. I have linked the repo here: https://github.com/LukasDeco/test-web3

**Comment by mschneider** [comment]
https://github.com/openbook-dex/openbook-v2/pull/257

ca you verify this patch solves your issue, or include a minimal reproduction to the repo?

**Comment by LukasDeco** [comment]
Yes I will take a look thank you so much

**Comment by LukasDeco** [comment]
@mschneider yes this looks good please merge and lmk when there is a new version. Thank you so much again.
