### ISSUE TITLE
Create Openbook Market ID error 

### ISSUE THREAD

**Issue by ByDA-Altas** [openbook-dex/openbook-v2#265]
![3a53a1548f26887586a28c48981aafa](https://github.com/openbook-dex/openbook-v2/assets/165327187/811db2ac-0cd4-4ee8-acc5-0a030cc4276e)
Wrong market ID was created, but the deduction was successful.

**Comment by riordanp** [comment]
unfortunately appears you were a victim of a scam, please see the list in discord for legit market creation tools
