### ISSUE TITLE
Error generate ID

### ISSUE THREAD

**Issue by PauloFaulhaber** [openbook-dex/openbook-v2#267]
Dear, There was an error in the transaction and there was no refund, what should I do?

TxID:

4LwH1JdtP6yRjGAgNSPV4ZvTF7Z31UMiAba5XHmtVMiY7J25f2QVgFdtnvB52sZdfCQ3rtma2L2dwTj6imBKH7XA

**Comment by mschneider** [comment]
your transaction includes a plain transfer of 0.2 sol to an address unknown to me. you have likely been scammed by an unaffiliated third party

**Comment by PauloFaulhaber** [comment]
Thanks man, is fake https://www.openbookdex.space/ ?
