### ISSUE TITLE
Permissioned markets

### ISSUE THREAD

**Issue by tomjohn1028** [openbook-dex/openbook-v2#33]
### What are they?
Permissioned markets stored a `market_authority` on the market data structure. Permissioned markets required all OpenOrders accounts to be owned by the Proxy program/market authority.  This gave authority the ability to 

A) Prune the order book (canceling orders and clearing out the book.
B) [never actually implemented on mainnet] Closing a market to reclaim the rent.  
C) Require all instructions to proxy through the Proxy program for preprocessing (e.g. authorization checks)

### Use cases

Permissioned markets were introduced into Serum V3 for at least 2 main reasons (there may be more, but these were the use cases I've encountered with other contributors). 

1. Ephemeral markets. A PsyFi options program can transparently implement closing DEX markets when an option expires.
2. Authorized markets. Some markets may require identity tokens or authorization to trade on.

**Comment by dankelleher** [comment]
I am at [Civic](civic.com) and worked with Armani on the initial implementation of Permissioned Markets in Serum. Here is a little background on the use-case for this feature

Markets may have constraints on who can place orders. For example, they may disallow traders in OFAC-sanctioned countries, or they may simply require traders to be whitelisted or KYCed.

This is a real possibility e.g. with MiCA regulations coming in next year in Europe that essentially requires KYC even for non-custodial wallets. Dexes that don't allow for these constraints may not be usable by institutional traders, banks etc.

We don't want to add anything like KYC into the dex itself, and we don't want to tie Openbook to any one implementation of these regulations on chain, but the dex should probably have a way to create markets that comply with them (and upcoming regulations).

The way Armani built this in Serum, was to abstract it into a Permissioned Markets proxy. Markets could be set up with a key that would have to cosign orders. This cosigner would typically be a PDA owned by a proxy, and traders would place orders via the proxy.

An important component is order-book "pruning" - permission to trade can also be removed, and in doing so, existing orders must also be removed. If, for example, a wallet makes an order, then that wallet shows up on some OFAC sanctions list, then traders filling that order would be in violation of US law and be liable to be prosecuted. The permissioned-markets proxy also had a prune function which would remove orders from the order-book for that wallet. Pruning was a permissionless crank operation.

The civic implementation of the proxy used a soulbound token (Civic Pass) to determine the right to trade. So the proxy checked for existence of a valid pass and pruned the order book if it was revoked.

Feel free to reach out if more details are needed about this feature. Anecdotally, we are speaking to interested parties quite frequently these days as people see regulations getting closer, who are interested in setting up permissioned markets using OpenBook (as well as other dexes on other chains).
