### ISSUE TITLE
Who is GluonicLedger Ltd?

### ISSUE THREAD

**Issue by metaproph3t** [openbook-dex/openbook-v2#4]
In the license file, it names an entity called 'GluonicLedger Ltd.' Who is this and what is their relationship to OpenBook?

**Comment by mschneider** [comment]
GluonicLedger is the $20 company the developers working on v2 set up to limit their liability arising from publishing the next version of the openbook source code. Wha are your concerns?

**Comment by metaproph3t** [comment]
Ok. I have no concerns, sir. I was curious and created an issue so that others who had the same question could see
