### ISSUE TITLE
Add order book pruning

### ISSUE THREAD

**Issue by metaproph3t** [openbook-dex/openbook-v2#50]
Issue [33](https://github.com/openbook-dex/openbook-v2/issues/33) discusses the need for an admin to be able to prune the order book for ephemeral markets. Normally, I would include this in the [addressing PR](https://github.com/openbook-dex/openbook-v2/pull/46), but order book pruning requires a new instruction (and corresponding tests), and this PR is already a bit plump.

Required changes:
- new `prune_order` instruction (batch or 1 order at a time?)
- new `prune_order_admin` field stored inside `Market`, checked against in the aforementioned `prune_order` instruction
- corresponding tests

**Comment by metaproph3t** [comment]
An alternative to a new instruction would be mutating the existing `cancel_order` instruction

**Comment by binyebarwe** [comment]
Imo it would be more clear the design of a new `prune_order` ix
